@host = http://localhost:8080
#@host = https://hdapp.ruslang.xyz
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjc4ODEzMzEyLCJleHAiOjE2Nzg4OTk3MTJ9.on6JPfnuTvktLTGbPFvOzvUorHdgSsObSOZQio4_EXo

POST {{host}}/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "swat0056@mail.ru",
  "password": "123"
}

###

POST {{host}}/api/auth/register HTTP/1.1
Content-Type: application/json

{
  "email": "ruziknf+23@ruzik.xyz",
  "full_name": "cringe cringe",
  "birth_date": "2002-01-01",
  "medical_organization_name": null,
  "confirmation_document_ids": [],
  "has_doctor_capabilities": false
}

###

POST {{host}}/api/auth/register HTTP/1.1
Content-Type: application/json

{
  "email": "ruziknf+5@ruzik.xyz",
  "full_name": "Anna Cutemon",
  "birth_date": "2002-01-01",
  "medical_organization_name": "DobroMed",
  "confirmation_document_ids": [],
  "has_doctor_capabilities": true
}

###

@verifyToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJydXppa25mKzNAcnV6aWsueHl6IiwiaWF0IjoxNjc3NzUwMzkzfQ.mlRw5rsRx7HFWWb9wNcuyuw8qLO3NJQRa1lEuH68BTY
GET {{host}}/api/auth/verify/{{verifyToken}} HTTP/1.1

####

POST {{host}}/api/media/upload HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="files"; filename="login.http"
Content-Type: image/png

< ./login.http

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="files"; filename="launch.json"
Content-Type: image/png

< ../launch.json
------WebKitFormBoundary7MA4YWxkTrZu0gW--

####

@file_id = 201228421542887429
@file_name = login.http
GET {{host}}/api/media/download/{{file_id}}/{{file_name}} HTTP/1.1
Authorization: Bearer {{token}}

####

# { has_doctor_capabilities: false }
#@b64Filters = eyJoYXNfZG9jdG9yX2NhcGFiaWxpdGllcyI6ZmFsc2V9

# { has_doctor_capabilities: true }
#@b64Filters = eyJoYXNfZG9jdG9yX2NhcGFiaWxpdGllcyI6dHJ1ZX0=

# { has_web3_address: false, has_doctor_capabilities: true, is_banned: false }
@b64Filters = eyJoYXNfd2ViM19hZGRyZXNzIjpmYWxzZSwiaGFzX2RvY3Rvcl9jYXBhYmlsaXRpZXMiOnRydWUsImlzX2Jhbm5lZCI6ZmFsc2V9


# { has_doctor_capabilities: true, is_banned: false }
#@b64Filters = eyJoYXNfZG9jdG9yX2NhcGFiaWxpdGllcyI6dHJ1ZSwiaXNfYmFubmVkIjpmYWxzZX0=

GET {{host}}/api/users?filters={{b64Filters}} HTTP/1.1
Authorization: Bearer {{token}}

####

GET {{host}}/api/users/by_id/3 HTTP/1.1
Authorization: Bearer {{token}}

####

GET {{host}}/api/users/by_web3_address/0xD6EDeB8cb9362C88F577aa37D9f5Ee27275DC93A HTTP/1.1
Authorization: Bearer {{token}}

####

PATCH {{host}}/api/users/1 HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "full_name": "cringe cringe2"
}

####

POST {{host}}/api/users/by_id/3/verify HTTP/1.1
Authorization: Bearer {{token}}

####

GET {{host}}/api/users/current/ HTTP/1.1
Authorization: Bearer {{token}}

####

GET {{host}}/api/statistics/ HTTP/1.1

####